/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cxria_ndkapplication_MainActivity */

#ifndef _Included_com_cxria_ndkapplication_MainActivity
#define _Included_com_cxria_ndkapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cxria_ndkapplication_MainActivity
 * Method:    add
 * Signature: (DD)Ljava/lang/String;
 */
JNIEXPORT jdouble JNICALL Java_com_cxria_ndkapplication_MainActivity_add
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_cxria_ndkapplication_MainActivity
 * Method:    minus
 * Signature: (DD)Ljava/lang/String;
 */
JNIEXPORT jdouble JNICALL Java_com_cxria_ndkapplication_MainActivity_minus
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_cxria_ndkapplication_MainActivity
 * Method:    multiply
 * Signature: (DD)Ljava/lang/String;
 */
JNIEXPORT jdouble JNICALL Java_com_cxria_ndkapplication_MainActivity_multiply
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_cxria_ndkapplication_MainActivity
 * Method:    divide
 * Signature: (DD)Ljava/lang/String;
 */
JNIEXPORT jdouble JNICALL Java_com_cxria_ndkapplication_MainActivity_divide
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
